build:
    nodes:
        php81:
            environment:
                php: '8.1'
            dependencies:
                override:
                    - composer install --prefer-dist --no-progress
            tests:
                override:
                    - command: XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=coverage.xml
                      coverage:
                          file: coverage.xml
                          format: clover
                    - vendor/bin/phpstan analyse --no-progress --memory-limit=512M
                    - vendor/bin/phpcs

        php82:
            environment:
                php: '8.2'
            dependencies:
                override:
                    - composer install --prefer-dist --no-progress
            tests:
                override:
                    - vendor/bin/phpunit
                    - vendor/bin/phpstan analyse --no-progress --memory-limit=512M
                    - vendor/bin/phpcs

        php83:
            environment:
                php: '8.3'
            dependencies:
                override:
                    - composer install --prefer-dist --no-progress
            tests:
                override:
                    - vendor/bin/phpunit
                    - vendor/bin/phpstan analyse --no-progress --memory-limit=512M
                    - vendor/bin/phpcs

        php84:
            environment:
                php: '8.4'
            dependencies:
                override:
                    - composer install --prefer-dist --no-progress
            tests:
                override:
                    - vendor/bin/phpunit
                    - vendor/bin/phpstan analyse --no-progress --memory-limit=512M
                    - vendor/bin/phpcs

        php85:
            environment:
                php: '8.5'
            dependencies:
                override:
                    - composer install --prefer-dist --no-progress
            tests:
                override:
                    - vendor/bin/phpunit
                    - vendor/bin/phpstan analyse --no-progress --memory-limit=512M
                    - vendor/bin/phpcs

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - vendor/*
        - tests/*
